/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.report.enums;

@org.apache.avro.specific.AvroGenerated
public enum EAction implements org.apache.avro.generic.GenericEnumSymbol<EAction> {

	INVALID,

	OPEN,

	CLOSE,

	CLOSE_TODAY,

	CLOSE_YESTERDAY;

	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
			"{\"type\":\"enum\",\"name\":\"EAction\",\"namespace\":\"io.horizon.trader.report.enums\",\"symbols\":[\"INVALID\",\"OPEN\",\"CLOSE\",\"CLOSE_TODAY\",\"CLOSE_YESTERDAY\"]}");

	public static org.apache.avro.Schema getClassSchema() {
		return SCHEMA$;
	}

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}
}
