/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.report.enums;

@org.apache.avro.specific.AvroGenerated
public enum EDirection implements org.apache.avro.generic.GenericEnumSymbol<EDirection> {

	INVALID,

	LONG,

	SHORT;

	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
			"{\"type\":\"enum\",\"name\":\"EDirection\",\"namespace\":\"io.horizon.trader.report.enums\",\"symbols\":[\"INVALID\",\"LONG\",\"SHORT\"]}");

	public static org.apache.avro.Schema getClassSchema() {
		return SCHEMA$;
	}

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}
}
