/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.transport.inbound;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** * 撤单 */
@org.apache.avro.specific.AvroGenerated
public class CancelOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2641904815061771827L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CancelOrder\",\"namespace\":\"io.horizon.trader.transport.inbound\",\"doc\":\"* 撤单\",\"fields\":[{\"name\":\"generateTime\",\"type\":\"long\"},{\"name\":\"sendTime\",\"type\":\"long\"},{\"name\":\"ordSysId\",\"type\":\"long\"},{\"name\":\"immediately\",\"type\":\"boolean\",\"default\":true},{\"name\":\"delayMillis\",\"type\":\"long\"},{\"name\":\"brokerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountId\",\"type\":\"int\"},{\"name\":\"subAccountId\",\"type\":\"int\"},{\"name\":\"strategyId\",\"type\":\"int\"},{\"name\":\"operatorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CancelOrder> ENCODER =
      new BinaryMessageEncoder<CancelOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CancelOrder> DECODER =
      new BinaryMessageDecoder<CancelOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CancelOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CancelOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CancelOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CancelOrder>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CancelOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CancelOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CancelOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CancelOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long generateTime;
  private long sendTime;
  private long ordSysId;
  private boolean immediately;
  private long delayMillis;
  private java.lang.String brokerId;
  private int accountId;
  private int subAccountId;
  private int strategyId;
  private java.lang.String operatorId;
  private java.lang.String message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CancelOrder() {}

  /**
   * All-args constructor.
   * @param generateTime The new value for generateTime
   * @param sendTime The new value for sendTime
   * @param ordSysId The new value for ordSysId
   * @param immediately The new value for immediately
   * @param delayMillis The new value for delayMillis
   * @param brokerId The new value for brokerId
   * @param accountId The new value for accountId
   * @param subAccountId The new value for subAccountId
   * @param strategyId The new value for strategyId
   * @param operatorId The new value for operatorId
   * @param message The new value for message
   */
  public CancelOrder(java.lang.Long generateTime, java.lang.Long sendTime, java.lang.Long ordSysId, java.lang.Boolean immediately, java.lang.Long delayMillis, java.lang.String brokerId, java.lang.Integer accountId, java.lang.Integer subAccountId, java.lang.Integer strategyId, java.lang.String operatorId, java.lang.String message) {
    this.generateTime = generateTime;
    this.sendTime = sendTime;
    this.ordSysId = ordSysId;
    this.immediately = immediately;
    this.delayMillis = delayMillis;
    this.brokerId = brokerId;
    this.accountId = accountId;
    this.subAccountId = subAccountId;
    this.strategyId = strategyId;
    this.operatorId = operatorId;
    this.message = message;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return generateTime;
    case 1: return sendTime;
    case 2: return ordSysId;
    case 3: return immediately;
    case 4: return delayMillis;
    case 5: return brokerId;
    case 6: return accountId;
    case 7: return subAccountId;
    case 8: return strategyId;
    case 9: return operatorId;
    case 10: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: generateTime = (java.lang.Long)value$; break;
    case 1: sendTime = (java.lang.Long)value$; break;
    case 2: ordSysId = (java.lang.Long)value$; break;
    case 3: immediately = (java.lang.Boolean)value$; break;
    case 4: delayMillis = (java.lang.Long)value$; break;
    case 5: brokerId = value$ != null ? value$.toString() : null; break;
    case 6: accountId = (java.lang.Integer)value$; break;
    case 7: subAccountId = (java.lang.Integer)value$; break;
    case 8: strategyId = (java.lang.Integer)value$; break;
    case 9: operatorId = value$ != null ? value$.toString() : null; break;
    case 10: message = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'generateTime' field.
   * @return The value of the 'generateTime' field.
   */
  public long getGenerateTime() {
    return generateTime;
  }


  /**
   * Sets the value of the 'generateTime' field.
   * @param value the value to set.
   */
  public void setGenerateTime(long value) {
    this.generateTime = value;
  }

  /**
   * Gets the value of the 'sendTime' field.
   * @return The value of the 'sendTime' field.
   */
  public long getSendTime() {
    return sendTime;
  }


  /**
   * Sets the value of the 'sendTime' field.
   * @param value the value to set.
   */
  public void setSendTime(long value) {
    this.sendTime = value;
  }

  /**
   * Gets the value of the 'ordSysId' field.
   * @return The value of the 'ordSysId' field.
   */
  public long getOrdSysId() {
    return ordSysId;
  }


  /**
   * Sets the value of the 'ordSysId' field.
   * @param value the value to set.
   */
  public void setOrdSysId(long value) {
    this.ordSysId = value;
  }

  /**
   * Gets the value of the 'immediately' field.
   * @return The value of the 'immediately' field.
   */
  public boolean getImmediately() {
    return immediately;
  }


  /**
   * Sets the value of the 'immediately' field.
   * @param value the value to set.
   */
  public void setImmediately(boolean value) {
    this.immediately = value;
  }

  /**
   * Gets the value of the 'delayMillis' field.
   * @return The value of the 'delayMillis' field.
   */
  public long getDelayMillis() {
    return delayMillis;
  }


  /**
   * Sets the value of the 'delayMillis' field.
   * @param value the value to set.
   */
  public void setDelayMillis(long value) {
    this.delayMillis = value;
  }

  /**
   * Gets the value of the 'brokerId' field.
   * @return The value of the 'brokerId' field.
   */
  public java.lang.String getBrokerId() {
    return brokerId;
  }


  /**
   * Sets the value of the 'brokerId' field.
   * @param value the value to set.
   */
  public void setBrokerId(java.lang.String value) {
    this.brokerId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public int getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public void setAccountId(int value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'subAccountId' field.
   * @return The value of the 'subAccountId' field.
   */
  public int getSubAccountId() {
    return subAccountId;
  }


  /**
   * Sets the value of the 'subAccountId' field.
   * @param value the value to set.
   */
  public void setSubAccountId(int value) {
    this.subAccountId = value;
  }

  /**
   * Gets the value of the 'strategyId' field.
   * @return The value of the 'strategyId' field.
   */
  public int getStrategyId() {
    return strategyId;
  }


  /**
   * Sets the value of the 'strategyId' field.
   * @param value the value to set.
   */
  public void setStrategyId(int value) {
    this.strategyId = value;
  }

  /**
   * Gets the value of the 'operatorId' field.
   * @return The value of the 'operatorId' field.
   */
  public java.lang.String getOperatorId() {
    return operatorId;
  }


  /**
   * Sets the value of the 'operatorId' field.
   * @param value the value to set.
   */
  public void setOperatorId(java.lang.String value) {
    this.operatorId = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Creates a new CancelOrder RecordBuilder.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.horizon.trader.transport.inbound.CancelOrder.Builder newBuilder() {
    return new io.horizon.trader.transport.inbound.CancelOrder.Builder();
  }

  /**
   * Creates a new CancelOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.horizon.trader.transport.inbound.CancelOrder.Builder newBuilder(io.horizon.trader.transport.inbound.CancelOrder.Builder other) {
    if (other == null) {
      return new io.horizon.trader.transport.inbound.CancelOrder.Builder();
    } else {
      return new io.horizon.trader.transport.inbound.CancelOrder.Builder(other);
    }
  }

  /**
   * Creates a new CancelOrder RecordBuilder by copying an existing CancelOrder instance.
   * @param other The existing instance to copy.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.horizon.trader.transport.inbound.CancelOrder.Builder newBuilder(io.horizon.trader.transport.inbound.CancelOrder other) {
    if (other == null) {
      return new io.horizon.trader.transport.inbound.CancelOrder.Builder();
    } else {
      return new io.horizon.trader.transport.inbound.CancelOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for CancelOrder instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CancelOrder>
    implements org.apache.avro.data.RecordBuilder<CancelOrder> {

    private long generateTime;
    private long sendTime;
    private long ordSysId;
    private boolean immediately;
    private long delayMillis;
    private java.lang.String brokerId;
    private int accountId;
    private int subAccountId;
    private int strategyId;
    private java.lang.String operatorId;
    private java.lang.String message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.horizon.trader.transport.inbound.CancelOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.generateTime)) {
        this.generateTime = data().deepCopy(fields()[0].schema(), other.generateTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sendTime)) {
        this.sendTime = data().deepCopy(fields()[1].schema(), other.sendTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ordSysId)) {
        this.ordSysId = data().deepCopy(fields()[2].schema(), other.ordSysId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.immediately)) {
        this.immediately = data().deepCopy(fields()[3].schema(), other.immediately);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.delayMillis)) {
        this.delayMillis = data().deepCopy(fields()[4].schema(), other.delayMillis);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[5].schema(), other.brokerId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.accountId)) {
        this.accountId = data().deepCopy(fields()[6].schema(), other.accountId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.subAccountId)) {
        this.subAccountId = data().deepCopy(fields()[7].schema(), other.subAccountId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[8].schema(), other.strategyId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.operatorId)) {
        this.operatorId = data().deepCopy(fields()[9].schema(), other.operatorId);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.message)) {
        this.message = data().deepCopy(fields()[10].schema(), other.message);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing CancelOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(io.horizon.trader.transport.inbound.CancelOrder other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.generateTime)) {
        this.generateTime = data().deepCopy(fields()[0].schema(), other.generateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sendTime)) {
        this.sendTime = data().deepCopy(fields()[1].schema(), other.sendTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ordSysId)) {
        this.ordSysId = data().deepCopy(fields()[2].schema(), other.ordSysId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.immediately)) {
        this.immediately = data().deepCopy(fields()[3].schema(), other.immediately);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.delayMillis)) {
        this.delayMillis = data().deepCopy(fields()[4].schema(), other.delayMillis);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[5].schema(), other.brokerId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.accountId)) {
        this.accountId = data().deepCopy(fields()[6].schema(), other.accountId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.subAccountId)) {
        this.subAccountId = data().deepCopy(fields()[7].schema(), other.subAccountId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[8].schema(), other.strategyId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.operatorId)) {
        this.operatorId = data().deepCopy(fields()[9].schema(), other.operatorId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.message)) {
        this.message = data().deepCopy(fields()[10].schema(), other.message);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'generateTime' field.
      * @return The value.
      */
    public long getGenerateTime() {
      return generateTime;
    }


    /**
      * Sets the value of the 'generateTime' field.
      * @param value The value of 'generateTime'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setGenerateTime(long value) {
      validate(fields()[0], value);
      this.generateTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'generateTime' field has been set.
      * @return True if the 'generateTime' field has been set, false otherwise.
      */
    public boolean hasGenerateTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'generateTime' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearGenerateTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sendTime' field.
      * @return The value.
      */
    public long getSendTime() {
      return sendTime;
    }


    /**
      * Sets the value of the 'sendTime' field.
      * @param value The value of 'sendTime'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setSendTime(long value) {
      validate(fields()[1], value);
      this.sendTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sendTime' field has been set.
      * @return True if the 'sendTime' field has been set, false otherwise.
      */
    public boolean hasSendTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sendTime' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearSendTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ordSysId' field.
      * @return The value.
      */
    public long getOrdSysId() {
      return ordSysId;
    }


    /**
      * Sets the value of the 'ordSysId' field.
      * @param value The value of 'ordSysId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setOrdSysId(long value) {
      validate(fields()[2], value);
      this.ordSysId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ordSysId' field has been set.
      * @return True if the 'ordSysId' field has been set, false otherwise.
      */
    public boolean hasOrdSysId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ordSysId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearOrdSysId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'immediately' field.
      * @return The value.
      */
    public boolean getImmediately() {
      return immediately;
    }


    /**
      * Sets the value of the 'immediately' field.
      * @param value The value of 'immediately'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setImmediately(boolean value) {
      validate(fields()[3], value);
      this.immediately = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'immediately' field has been set.
      * @return True if the 'immediately' field has been set, false otherwise.
      */
    public boolean hasImmediately() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'immediately' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearImmediately() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'delayMillis' field.
      * @return The value.
      */
    public long getDelayMillis() {
      return delayMillis;
    }


    /**
      * Sets the value of the 'delayMillis' field.
      * @param value The value of 'delayMillis'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setDelayMillis(long value) {
      validate(fields()[4], value);
      this.delayMillis = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'delayMillis' field has been set.
      * @return True if the 'delayMillis' field has been set, false otherwise.
      */
    public boolean hasDelayMillis() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'delayMillis' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearDelayMillis() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'brokerId' field.
      * @return The value.
      */
    public java.lang.String getBrokerId() {
      return brokerId;
    }


    /**
      * Sets the value of the 'brokerId' field.
      * @param value The value of 'brokerId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setBrokerId(java.lang.String value) {
      validate(fields()[5], value);
      this.brokerId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'brokerId' field has been set.
      * @return True if the 'brokerId' field has been set, false otherwise.
      */
    public boolean hasBrokerId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'brokerId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearBrokerId() {
      brokerId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public int getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setAccountId(int value) {
      validate(fields()[6], value);
      this.accountId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearAccountId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'subAccountId' field.
      * @return The value.
      */
    public int getSubAccountId() {
      return subAccountId;
    }


    /**
      * Sets the value of the 'subAccountId' field.
      * @param value The value of 'subAccountId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setSubAccountId(int value) {
      validate(fields()[7], value);
      this.subAccountId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'subAccountId' field has been set.
      * @return True if the 'subAccountId' field has been set, false otherwise.
      */
    public boolean hasSubAccountId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'subAccountId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearSubAccountId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'strategyId' field.
      * @return The value.
      */
    public int getStrategyId() {
      return strategyId;
    }


    /**
      * Sets the value of the 'strategyId' field.
      * @param value The value of 'strategyId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setStrategyId(int value) {
      validate(fields()[8], value);
      this.strategyId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'strategyId' field has been set.
      * @return True if the 'strategyId' field has been set, false otherwise.
      */
    public boolean hasStrategyId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'strategyId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearStrategyId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'operatorId' field.
      * @return The value.
      */
    public java.lang.String getOperatorId() {
      return operatorId;
    }


    /**
      * Sets the value of the 'operatorId' field.
      * @param value The value of 'operatorId'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setOperatorId(java.lang.String value) {
      validate(fields()[9], value);
      this.operatorId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'operatorId' field has been set.
      * @return True if the 'operatorId' field has been set, false otherwise.
      */
    public boolean hasOperatorId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'operatorId' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearOperatorId() {
      operatorId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder setMessage(java.lang.String value) {
      validate(fields()[10], value);
      this.message = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public io.horizon.trader.transport.inbound.CancelOrder.Builder clearMessage() {
      message = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public CancelOrder build() {
      try {
        CancelOrder record = new CancelOrder();
        record.generateTime = fieldSetFlags()[0] ? this.generateTime : (java.lang.Long) defaultValue(fields()[0]);
        record.sendTime = fieldSetFlags()[1] ? this.sendTime : (java.lang.Long) defaultValue(fields()[1]);
        record.ordSysId = fieldSetFlags()[2] ? this.ordSysId : (java.lang.Long) defaultValue(fields()[2]);
        record.immediately = fieldSetFlags()[3] ? this.immediately : (java.lang.Boolean) defaultValue(fields()[3]);
        record.delayMillis = fieldSetFlags()[4] ? this.delayMillis : (java.lang.Long) defaultValue(fields()[4]);
        record.brokerId = fieldSetFlags()[5] ? this.brokerId : (java.lang.String) defaultValue(fields()[5]);
        record.accountId = fieldSetFlags()[6] ? this.accountId : (java.lang.Integer) defaultValue(fields()[6]);
        record.subAccountId = fieldSetFlags()[7] ? this.subAccountId : (java.lang.Integer) defaultValue(fields()[7]);
        record.strategyId = fieldSetFlags()[8] ? this.strategyId : (java.lang.Integer) defaultValue(fields()[8]);
        record.operatorId = fieldSetFlags()[9] ? this.operatorId : (java.lang.String) defaultValue(fields()[9]);
        record.message = fieldSetFlags()[10] ? this.message : (java.lang.String) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CancelOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<CancelOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CancelOrder>
    READER$ = (org.apache.avro.io.DatumReader<CancelOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.generateTime);

    out.writeLong(this.sendTime);

    out.writeLong(this.ordSysId);

    out.writeBoolean(this.immediately);

    out.writeLong(this.delayMillis);

    out.writeString(this.brokerId);

    out.writeInt(this.accountId);

    out.writeInt(this.subAccountId);

    out.writeInt(this.strategyId);

    out.writeString(this.operatorId);

    out.writeString(this.message);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.generateTime = in.readLong();

      this.sendTime = in.readLong();

      this.ordSysId = in.readLong();

      this.immediately = in.readBoolean();

      this.delayMillis = in.readLong();

      this.brokerId = in.readString();

      this.accountId = in.readInt();

      this.subAccountId = in.readInt();

      this.strategyId = in.readInt();

      this.operatorId = in.readString();

      this.message = in.readString();

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.generateTime = in.readLong();
          break;

        case 1:
          this.sendTime = in.readLong();
          break;

        case 2:
          this.ordSysId = in.readLong();
          break;

        case 3:
          this.immediately = in.readBoolean();
          break;

        case 4:
          this.delayMillis = in.readLong();
          break;

        case 5:
          this.brokerId = in.readString();
          break;

        case 6:
          this.accountId = in.readInt();
          break;

        case 7:
          this.subAccountId = in.readInt();
          break;

        case 8:
          this.strategyId = in.readInt();
          break;

        case 9:
          this.operatorId = in.readString();
          break;

        case 10:
          this.message = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










