/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.transport.enums;
@org.apache.avro.specific.AvroGenerated
public enum TdxOrdLevel implements org.apache.avro.generic.GenericEnumSymbol<TdxOrdLevel> {
  CHILD, PARENT, STRATEGY, GROUP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TdxOrdLevel\",\"namespace\":\"io.horizon.trader.transport.enums\",\"symbols\":[\"CHILD\",\"PARENT\",\"STRATEGY\",\"GROUP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
