/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.transport.enums;
@org.apache.avro.specific.AvroGenerated
public enum TOrdValid implements org.apache.avro.generic.GenericEnumSymbol<TOrdValid> {
  GTC, GTD, GFD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TOrdValid\",\"namespace\":\"io.horizon.trader.transport.enums\",\"symbols\":[\"GTC\",\"GTD\",\"GFD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
